### PR TITLE
Updating get_meta to handle 3-col info on filters and indicators

### PR DESCRIPTION
**Pull request by rmbielby**
# Brief overview of changes

The meta data returned by the API has been changed to include id, col_name and label for filter and indicator columns (where previously it was just col_name and label). This updates `get_meta()` to account for the change to the API behaviour.

## Why are these changes being made?

Change in API behaviour

## Detailed description of changes

I've updated `parse_meta_filter_columns()` to account for the extra column and to label them up appropriately in the returned meta data frame.

Bonus change: I originally wrote `parse_meta_indicator_columns()` for `get_meta()`, but realised that `parse_meta_filter_columns()` did an identical job, so never actually used it. I intended to go back and delete it before finishing `get_meta()` but must have forgotten, so done that now.

Also updated the tests to account for the change.

### CODE REVIEW

**Review by cjrace — CHANGES_REQUESTED** [review]
One minor comment for somewhere else I think you need to update - should this be col_id rather than col_name?

image

**Comment by cjrace** [comment]
Possibly also a question for your next work whether having both col_id and col_name would be helpful in the meta response for filter_items. It's not necessary, but could be nice for users, and might be helpful for some of the processing (or might not make a difference!)

**Comment by rmbielby** [comment]
> One minor comment for somewhere else I think you need to update - should this be col_id rather than col_name?
> 
> image

Made that change now.

**Comment by rmbielby** [comment]
> Possibly also a question for your next work on the tidying / swapping of ids to labels as to whether having both col_id and col_name would be helpful in the meta response for filter_items. It's not necessary, but could be nice for users, and might be helpful for some of the processing (or might not make a difference!)

Maybe, I could argue myself either way I think. Think I'd either keep it as it is or merge filter_columns and filter_items together and wouldn't want the halfway ground of the col_names being repeated in two different places. At the moment, I feel like it's easy enough for a user to do a left join on col_id if they want everything together, so marginally favour keeping the status quo.

**Review by cjrace — APPROVED** [review]

**Pull request merged**
